### ISSUE TITLE
MacOS: pixmaps not loading

### ISSUE THREAD

**Issue by mindhells** [fract4d/gnofract4d#126]
Pixmaps are not being loaded in MacOS environment (10.15.3).

![Captura de pantalla 2020-06-08 a las 10 47 57](https://user-images.githubusercontent.com/1893197/84016818-bfa8cd00-a975-11ea-83d4-93405e2fcf89.png)

![Captura de pantalla 2020-06-08 a las 10 48 27](https://user-images.githubusercontent.com/1893197/84016831-c2a3bd80-a975-11ea-9870-cf4a233f6ab3.png)

**Comment by cjmayo** [comment]
Summary:
The application pixmaps are loaded from share/gnofract4d/pixmaps.
The logo on the About dialog is loaded by GTK from the desktop environment theme (the advantages there being it also supports the icon displayed by the environment in e.g. task switcher, application list or menus and manages different sized icons).

Info from #127:
The share folder is under /usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg. This share folder contains the manual and also the pixmaps

I don't know if this is useful, but where does MacOS place the application pixmaps if installed with:
`setup.py install --single-version-externally-managed`

**Comment by cjmayo** [comment]
Possibly even:
`setup.py install --single-version-externally-managed --root=/`

https://stackoverflow.com/a/33791008

**Comment by mindhells** [comment]
It's interesting because when I do that no icon are drawn in the user interface (it also fails to find color maps or any other data file). While doing a simple install only a few icons are missing.

**with `setup.py install --single-version-externally-managed --root=/`**

```shell
...
copying pixmaps/logo/48x48/gnofract4d.png -> /usr/local/share/pixmaps
copying pixmaps/logo/16x16/gnofract4d.png -> /usr/local/share/icons/hicolor/16x16/apps
copying pixmaps/logo/32x32/gnofract4d.png -> /usr/local/share/icons/hicolor/32x32/apps
copying pixmaps/logo/48x48/gnofract4d.png -> /usr/local/share/icons/hicolor/48x48/apps
creating /usr/local/share/icons/hicolor/64x64
creating /usr/local/share/icons/hicolor/64x64/apps
copying pixmaps/logo/64x64/gnofract4d.png -> /usr/local/share/icons/hicolor/64x64/apps
creating /usr/local/share/icons/hicolor/128x128
creating /usr/local/share/icons/hicolor/128x128/apps
copying pixmaps/logo/128x128/gnofract4d.png -> /usr/local/share/icons/hicolor/128x128/apps
copying pixmaps/logo/256x256/gnofract4d.png -> /usr/local/share/icons/hicolor/256x256/apps
copying gnofract4d.desktop -> /usr/local/share/applications
copying LICENSE -> /usr/local/share/doc/gnofract4d/
copying README.md -> /usr/local/share/doc/gnofract4d/
running install_egg_info
running egg_info
writing gnofract4d.egg-info/PKG-INFO
writing dependency_links to gnofract4d.egg-info/dependency_links.txt
writing top-level names to gnofract4d.egg-info/top_level.txt
reading manifest file 'gnofract4d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'gnofract4d.egg-info/SOURCES.txt'
Copying gnofract4d.egg-info to /usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7.egg-info
running install_scripts
copying build/scripts-3.7/gnofract4d -> /usr/local/bin
changing mode of /usr/local/bin/gnofract4d to 755
````
![Captura de pantalla 2020-06-10 a las 9 29 19](https://user-images.githubusercontent.com/1893197/84245513-1096fd80-aafd-11ea-937a-93948232b2d3.png)

**with `setup.py install`**
```bash
...
creating build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/gnofract4d -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/scripts/gnofract4d to 755
copying gnofract4d.egg-info/PKG-INFO -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying gnofract4d.egg-info/SOURCES.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying gnofract4d.egg-info/dependency_links.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying gnofract4d.egg-info/top_level.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.15-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
fract4d.__pycache__.fract4d_stdlib.cpython-37: module references __file__
fract4d.__pycache__.fract4dc.cpython-37: module references __file__
fract4d.__pycache__.fractconfig.cpython-37: module references __file__
fract4d_compiler.__pycache__.fc.cpython-37: module references __file__
fract4d_compiler.__pycache__.lex.cpython-37: module references __file__
fract4d_compiler.__pycache__.lex.cpython-37: module MAY be using inspect.getsourcefile
fract4d_compiler.__pycache__.yacc.cpython-37: module references __file__
fract4d_compiler.__pycache__.yacc.cpython-37: module MAY be using inspect.getsourcefile
fract4d_compiler.__pycache__.yacc.cpython-37: module MAY be using inspect.stack
fract4dgui.__pycache__.main_window.cpython-37: module references __file__
fract4dgui.__pycache__.utils.cpython-37: module MAY be using inspect.stack
creating 'dist/gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg' and adding 'build/bdist.macosx-10.15-x86_64/egg' to it
removing 'build/bdist.macosx-10.15-x86_64/egg' (and everything under it)
Processing gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg
removing '/usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg
Extracting gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg to /usr/local/lib/python3.7/site-packages
gnofract4d 4.2 is already the active version in easy-install.pth
Installing gnofract4d script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7-macosx-10.15-x86_64.egg
Processing dependencies for gnofract4d==4.2
Finished processing dependencies for gnofract4d==4.2
```

Now after a normal install I cannot launch Gnofract4d, it throws this error:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/gnofract4d", line 4, in <module>
    __import__('pkg_resources').run_script('gnofract4d==4.2', 'gnofract4d')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/gnofract4d' not found in metadata at '/usr/local/lib/python3.7/site-packages/gnofract4d-4.2-py3.7.egg-info'
```

To make it work back I had to do [the following](https://stackoverflow.com/questions/3582715/python-install-uninstall-easy-install):
- delete the gnofract4d egg from `/usr/local/lib/python3.7/site-packages`
- install normal `setup.py install`
- `easy_install-3.7 -m gnofract4d`

**Comment by cjmayo** [comment]
I hope #131 will work with a `--single-version-externally-managed` (maybe the --root is critical too) installation.

That is for the application pixmaps, maps, formulas and manual.

I don't know in general if /usr/share/icons/hicolor, /usr/share/mime/packages/gnofract4d-mime.xml and /usr/share/applications/gnofract4d.desktop (or their /usr/local equivalents) work on MacOS. For #131 this would affect the logo in the About dialog.

**Comment by mindhells** [comment]
When using `--single-version-externally-managed` I'm required to provide root or record arguments too.

```bash
error: You must specify --record or --root when building system packages
```

In regard to #131 the install option has one interesting flag `--install-data`... don't know if you can default that value depending on the system.

**Comment by edyoung** [comment]
I am also finding that with current main branch gnofract4d is unable to find various files after install: the pixmaps, the help file, and basic.map while drawing the initial image.

This is with Ubuntu 18.04, Python 3.6.

Setup.py install writes the files under  

`/usr/local/lib/python3.6/dist-packages/gnofract4d-4.2-py3.6-linux-x86_64.egg/share/gnofract4d/`

then `help/index.html` is the doc, 
`pixmaps/*.png` contain the pixmaps

The main script is written to /usr/local/bin/gnofract4d

Ideally I don't want users to have to mess arround with --single-version-externally-managed etc.

Seems to me we either treat these files as part of the extension, and resolve their locations relative to the __file__ of the fract4d module, or take them out of the extension and associate them with the binary.

**Comment by cjmayo** [comment]
[pkg_resources](https://setuptools.readthedocs.io/en/latest/pkg_resources.html) is an alternative to relative paths for the Python package.

But there are files for gnofract4d and files for the desktop environment (pixmaps/gnofract4d.png, icons/hicolor/, applications/gnofract4d.desktop, mime/packages/gnofract4d-mime.xml) - these have got to be installed in /usr, /usr/local or ~/.local (on Linux).

The only change that looks a likely suspect to me is:
3e02eea ("Remove buildtools package (#104)", 2020-05-21)

The code comments suggested this was about executables, but maybe (at least part of it) was affecting data. Does reverting that fix bring back the old behaviour? I don't see it because I am using Gentoo Linux to install which is setting root in an [install] section of a pydistutils.cfg automatically for me which I guess is fixing this.

This is what drove me to try Meson...

**Comment by cjmayo** [comment]
Maybe there is a simple solution after all:
`pip3 install .`

Looks like running `setup.py` is bringing in all disutils stuff [1], and old use of setuptools the egg [2].
[1] https://www.python.org/dev/peps/pep-0370/#id32
[2] https://setuptools.readthedocs.io/en/latest/setuptools.html#id24


This also gives access to `pip3 uninstall gnofract4d` and `pip3 show gnofract4d`.

Is pip easily availabe on MacOS? Previously I had found that you needed ``get-pip.py`` from https://pip.pypa.io/en/stable/installing/.

**Comment by mindhells** [comment]
> Is pip easily availabe on MacOS? Previously I had found that you needed `get-pip.py` from https://pip.pypa.io/en/stable/installing/.

I had no trouble with installing pip, it's installed when you do `brew install python`.

I tried pip install and uninstall and it works fine, but I still have the same issue with the icons:

![Captura de pantalla 2020-07-03 a las 9 32 05](https://user-images.githubusercontent.com/1893197/86449569-49974c00-bd10-11ea-9205-873de7e2e0cf.png)

**Comment by cjmayo** [comment]
> I had no trouble with installing pip, it's installed when you do `brew install python`.
> 

Good to know.

> I tried pip install and uninstall and it works fine, but I still have the same issue with the icons:
> 

OK, so these are actually a third type of icons - stock icons loaded from the desktop theme.

First step: is the logo in the about dialog OK now? (that is an icon we have saved into the desktop environment).

Second step: Install e.g. adwaita-icon-theme from brew to get the stock icons? This is a guess, any theme providing compatible undo and redo icons would be OK.

**Comment by mindhells** [comment]
1- The logo in the about dialog it's shown correctly after `pip3 install .`

2- Then after `brew install adwaita-icon-theme` the stock icons are finally there :)

![Captura de pantalla 2020-07-03 a las 19 14 38](https://user-images.githubusercontent.com/1893197/86491081-92c3bc00-bd61-11ea-8dc9-ff7ea4c5084e.png)

Btw when I installed the icon theme, the `libffi` dependency got updated and gnofract couldn't be launched, throwing this error:
```bash
A fatal error occurred:
	dlopen(/usr/local/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so, 10): 
Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so
  Reason: image not found
```
I found this [issue](https://github.com/platformio/platform-lattice_ice40/issues/7) from another project with the exact same problem. The workaround that worked for mi is:
```bash
cd /usr/local/opt/libffi/lib
ln -s libffi.7.dylib libffi.6.dylib
```
I don't like it too much but it worked.

For what is worth this issue is solved for me. I will create a PR to update the docs with this info and then close this asap.

Thanks!

**Comment by edyoung** [comment]
very weird there is any relation between icon theme and ffi? Possibly if you recompile after installing the them it will link against 1.7 and the symlink hack wouldn't be required

**Comment by mindhells** [comment]
> very weird there is any relation between icon theme and ffi? Possibly if you recompile after installing the them it will link against 1.7 and the symlink hack wouldn't be required

I think it’s something to do with hombrew and dependency management. In this case, the gi wrapper is trying to load an older version of the libffi because this’s been updated.

I guess libffi is not a 1st level dependency of the icon theme but it’s related with one of them. I will investigate further to see if there’s a better solution.

**Comment by DX-MON** [comment]
libffi is most likely caused by Adwaitia.. The icon set brings in the theme engine. You might find it better to instead install the icon-only theme [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) as GTK just wants to find the correctly named icon files and doesn't actually care what theme they come from.

This points to perhaps bundling a basic icon of the right name as a fallback in case a theme-correct one can't be found

**Comment by cjmayo** [comment]
> libffi is most likely caused by Adwaitia.. The icon set brings in the theme engine. 

Are you sure? Isn't that a GTK 2 thing? I think this is just icons now - but when installing it is using gtk-update-icon-cache causing a dependency on GTK 3 https://github.com/Homebrew/homebrew-core/blob/c67068b9b0f6333ae2f039fb4101665d0e22cc37/Formula/adwaita-icon-theme.rb#L23, which is then pulling in glib and then libffi. I'm guessing on how Homebrew is working - so treat this with caution, in case there are some other consequences - but maybe just rebuilding pygobject3 will be enough, it looks like adwaita-icon-theme indirectly pulls in most other things that use libffi.

This issue was very useful, made me find out what pip was really about - seems like the way to go for now, you can even `pip3 install https://github.com/fract4d/gnofract4d/releases/download/v4.2/gnofract4d-4.2.tar.gz`.

**Comment by DX-MON** [comment]
Ah, fair point about gtk-update-icon-cache.. theme engines are still a thing in GTK3, but given what youv'e provided, I think you're right about what's causing libffi to get pulled in..

pip can ingest Git repos directly (git+https://github.com/fract4d/gnoforact4d), dist tarballs as in your post, local clones, etc.. you can also `python3 setup.py bdist_wheel` to get a modern .whl file to then install in the dist/ subdir of your project. It's kinda crazy as it's more "what can't pip do?"

**Comment by mindhells** [comment]
1- I reverted the symbolic link hack.
2- Then I reinstalled pygobject3 `brew reinstall pygobject3`
3- Lastly I had to `pip3 install PyGObject`.

The 3rd step I had to do because otherwise I got this error:
```bash
A fatal error occurred:
	module 'gi' has no attribute 'require_version'


Traceback (most recent call last):
  File "/usr/local/bin/gnofract4d", line 92, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/gnofract4d", line 40, in main
    gtkmain(userConfig, opts)
  File "/usr/local/bin/gnofract4d", line 48, in gtkmain
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

Which is strange because according to the manual https://pygobject.readthedocs.io/en/latest/getting_started.html you don't need to do that in MacOS
Probably I'm missing something ...

**Comment by edyoung** [comment]
I think we can call this resolved, but don't have a Mac at hand
