### ISSUE TITLE
Distribute built manual in help/ not manual/public/

### ISSUE THREAD

**Issue by cjmayo** [fract4d/gnofract4d#132]
formulas, maps and pixmaps are already in a top-level directory in the repository and distribution that matches the subdirectory they are installed in in $(prefix)/share/gnofract4d. If the manual was moved similarly then we could simplify the code further:

https://github.com/fract4d/gnofract4d/blob/c8277f65acdcd55a01f2c7b37e1e64fdc9daa5a2/fract4d/fractconfig.py#L139

local_dir and installed_dir would always be the same, allowing us to only use a single value.

Don't know how easy it is. I tried setting `publishDir = "../help"` in manual/config.toml but only some files seemed to be created in the new directory.

(Directory could e.g. be manual/ instead of help/)

**Comment by edyoung** [comment]
I think this could be changed by updating the options passed to hugo in createdocs.py

**Comment by cjmayo** [comment]
That works. My problem was I hadn't done init and update on the submodule. I guess it has to be help/ as manual/ is already taken?
