### ISSUE TITLE
Is fractutils folder really needed?

### ISSUE THREAD

**Issue by josebailo** [fract4d/gnofract4d#148]
I've checked it and seems that fractutils folder is not needed in the project so, could it be removed?

If it contains scripts or information you want to keep maybe would have more sense to create a new utils repository in the [organization](https://github.com/fract4d).

What do you think?

**Comment by edyoung** [comment]
Those files are all old experiments, no longer used by the main code.

- makemap.py was an attempt to find the dominant colors in an image file and then make a palette out of them, but was never finished
- get.py was used for flickr integration before I removed that 
- slave.py (ouch, what was I thinking? was to run a child process so it didn't block gtk main loop)

I think I'll just delete it all.
