### ISSUE TITLE
Top menu is gone in MacOS

### ISSUE THREAD

**Issue by mindhells** [fract4d/gnofract4d#198]
Environment: MacOS Catalina 10.15.7, python 3.9.0

Top menu is gone after applying #187 

Before:
![](https://user-images.githubusercontent.com/1893197/102902879-72023680-4467-11eb-9541-4be960fad93b.png)

After:
![](https://user-images.githubusercontent.com/1893197/102902894-762e5400-4467-11eb-9921-a316447ba86d.png)

**Comment by cjmayo** [comment]
Glad you found that...

I've created #200 based on reading the GTK docs, this will still be different to before - now the application window should be up in the standard Mac menu bar. Please test.

**Comment by cjmayo** [comment]
To be 100% clear, the screenshots show the application window - the gnofract4d menus are not shown at the top of the screen with the menu bar with the Apple menu?

**Comment by mindhells** [comment]
> To be 100% clear, the screenshots show the application window - the gnofract4d menus are not shown at the top of the screen with the menu bar with the Apple menu?

I think I just missed it because I was used to the old approach, but actually the version in master branch is ok, the menu it's shown like this:
![Captura de pantalla 2021-01-19 a las 10 54 00](https://user-images.githubusercontent.com/1893197/105025102-c5ef4380-5a44-11eb-9afe-5051f0259005.png)

So this issue can be closed and the #200 does not need to be merged because it puts everything under the Python menu, which I think is way less usable.

Sorry for the confusion.

**Comment by cjmayo** [comment]
Well, otherwise us non-Mac users wouldn't know it actually worked!

Having `Python` at the top of it doesn't help. Maybe starting from a `Gnofract4D` symlink might work.
