### ISSUE TITLE
Formula search path and lowercase bug

### ISSUE THREAD

**Issue by retrue** [fract4d/gnofract4d#239]
I downloaded yesterday the last code with the last commit, I compiled and ran the program from that same folder instead of doing a full installation.
The program works but I have a problem with paths and folder names that I didn't have before.
I have two packs of formulas, called Fractint and UF inside of the directory Gnofract4D/formulas.
In Edit/Preferences/Compiler/Formula Search Path, when I try and add the Fractint and UF folders, Gnofract4D cannot see the formulas inside. If I close and open again the Compiler preferences and look I find that the path there appears written in lowercases.
Instead of /home/myname/FractalSoft/Gnofract4d/formulas/UF it will appear as /home/myname/fractalsoft/gnofract4d/formulas/uf
The only way I found to make those formulas work is to rename those folders in my file system to make them lowercase.

**Comment by cjmayo** [comment]
I believe this is fixed by #240. Additional confirmation always welcome!
