### ISSUE TITLE
Difficulty with setup

### ISSUE THREAD

**Issue by userofgithub58** [fract4d/gnofract4d#255]
Hi,

I'm trying to install Fract4d, following the basic installation commands of Readme.
An error occurs using the command setup.py build : 

Traceback (most recent call last):
  File "/home/.../gnofract4d-4.3/setup.py", line 173, in <module>
    get_files("maps", ".map") +
  File "/home/.../gnofract4d-4.3/setup.py", line 136, in get_files
    return [os.path.join(dir, x) for x in os.listdir(dir) if x.endswith(ext)]
FileNotFoundError: [Errno 2] No such file or directory: 'maps'

I've got python installed with the requirement commands, and I'm on Ubuntu 22.04.

Is there a way to solve this issue ?

Thank you

**Comment by cjmayo** [comment]
You don't say what you downloaded and how you unpacked it, but it appears something has gone wrong there as it can't find the maps directory.

It looks like you have tried version 4.3. You can download the latest code from:
https://github.com/fract4d/gnofract4d/archive/master.tar.gz

Note the dependencies have changed a bit.

**Comment by userofgithub58** [comment]
Thanks for the response.
I unpacked it using archive manager Engrampa.
I also tried it manually using : tar -xzvf file.tar -C /.../, with no changes.

I used the version 4.3 indeed, from the Gnofract website [https://fract4d.github.io/gnofract4d/]. The result is the same with the master version, with different lines of error (resp. line 186 and line 148). I can also access the maps directory in the extracted files, so it is there.

Is there something else I can do ?

Thank you

**Comment by cjmayo** [comment]
Next guess: are you actually running `./setup.py build` (or indeed `python3 setup.py build`), that is from within the unpacked directory?

Else, please report exactly what commands you are using because otherwise it is a bit of a guessing game.

**Comment by dragonmux** [comment]
Similarly it would be useful to know what version of Python and Pip you're using (`python3 --version`, `pip3 --version`) to help pinpoint and reproduce the results

**Comment by userofgithub58** [comment]
That was a good guess! Running `python3 setup.py build` directly from the unpacked directory did the work.
Thanks for the nice help :)
