### ISSUE TITLE
Missing OrgForm.

### ISSUE THREAD

**Issue by da2ce7** [fract4d/gnofract4d#50]
Website links to file:

http://home.att.net/~Paul.N.Lee/OrgForm.html

The website is lost except for the wayback machine;

https://web.archive.org/web/20100310162016/http://home.att.net/~Paul.N.Lee/OrgForm.html

Unfortunately, the wayback machine didn’t take any copies of the zip file:

https://web.archive.org/web/20131011135242/http://www.nahee.com/Fractals/FractInt/ORGFORM.ZIP

And;

Paul unfortunately is now deceased.

https://www.linkedin.com/in/paul-n-lee-375b7a3

So, if anyone has a copy of the file, for prosperity, it would be nice to re-upload it.

**Comment by edyoung** [comment]
I'm sorry to hear about Paul :-(

Will be glad update the website with a link (or host myself) if someone has a copy.

**Comment by da2ce7** [comment]
I have found a mirror of the updated version of the website on the wayback machine:

https://web.archive.org/web/20170706035213/http://www.nahee.com/PNL/

Including the OrgForm page:

https://web.archive.org/web/20170809064351/http://www.nahee.com/PNL/OrgForm.html

and the ORGFORM.ZIP

https://web.archive.org/web/20160807081118/http://www.nahee.com/Fractals/ORGFORM.ZIP

😀

**Comment by edyoung** [comment]
I uploaded a copy of the files from orgform to github.com/fract4d/formulas

The idea is to make it possible to clone that repo from inside Gnofract 4D and thereby get these and many other formulas easily.
