### ISSUE TITLE
Rewritten Git History, Including Historical History from CVS

### ISSUE THREAD

**Issue by da2ce7** [fract4d/gnofract4d#57]
The old cvs commit history was sadly misplaced when with project transitioned to Git.

I have taken an effort to restore this old history in a methodical way.

Please See:
https://github.com/da2ce7/gnofract4d/tree/master_upon_cvs

Steps Taken:
- Found old CVS History:

https://sourceforge.net/p/gnofract4d/cvs/

- Used reposurgeon to convert the old CVS to Git.

Info and Makefile used here:
https://github.com/da2ce7/gnofract4d/tree/master_upon_cvs_notes/doc/cvs_to_git_info

- Made extra commits to remove files that were not re-included:

53aadab6385c627b2168665adb6d052825f2174c remove 'elephant-valley' website testing ground
3df71322cf374d13c80183bffac5d8e2fbb76993 remove old fractal parameter files
ed3c35a3cef3961361e79a33a4c563ab14a03ed9 remove old utility files
dd18635f9f77fbb6b131d8d2c45f227ef733e352 remove old translation files
2b27bd53c43f5fe8146895ece5b5b680babceed9 now we use git

- Rebased upon old commits:

used Script:
https://github.com/da2ce7/gnofract4d/blob/master_upon_cvs_notes/doc/cvs_to_git_info/rebase_script.sh

and notes:
https://github.com/da2ce7/gnofract4d/blob/master_upon_cvs_notes/doc/cvs_to_git_info/notes_on_rebase.md

- Compared Output to Verify that the files of the most-recent commit hasn't changed:

`git show -s --format="%T" 0e414d3d4b37f9fe7c38693532f7a3eb4a8e341d
4d3cbbae4375c0a88b52f1270d4e68e27672e7b8` https://github.com/edyoung/gnofract4d/commit/0e414d3d4b37f9fe7c38693532f7a3eb4a8e341d
`git show -s --format="%T" 8575586b1dbc5c6b52cdde9a072dc27dc393ba16
4d3cbbae4375c0a88b52f1270d4e68e27672e7b8` (https://github.com/da2ce7/gnofract4d/commit/8575586b1dbc5c6b52cdde9a072dc27dc393ba16)

How to Update:
If you have the desire, you may wish to move the offical repository to this version:

User the commands:

1. Add me as one of your remotes:
`git remote add da2ce7 git@github.com:da2ce7/gnofract4d.git`
2. Fetch Commits and Tags:
`git fetch --tags da2ce7`
2. Make Backup of Master:
`git checkout -b original_master master`
3. Make Branch for New Master:
`git checkout -b new_master da2ce7/master_upon_cvs`
4. Verify that the file tree is the same:
`git show -s --format="%T" original_master`
`git show -s --format="%T" new_master`
(compare hashes as to be the same)
5. Hard Reset your master to the new_master:
`git checkout master`
`git reset --hard new_master`
6. Final, force-push the new master to github
`git push --force`
`git push --tags`

I hope you find this interesting, I believe it important to keep this old history available.

**Comment by edyoung** [comment]
Thanks! Really appreciate the effort. To be honest I'm a little surprised anyone cares enough about the ancient pre-GitHub history of the project to take the trouble. Unfortunately it may take a while for me to look at the steps you've listed above because I'm rather busy at the moment. Hopefully this will not impede any new development in the interim.

**Comment by da2ce7** [comment]
This is fine. I will merge any accepted the pull requests into my master_upon_cvs branch also.

Updated hashes after https://github.com/edyoung/gnofract4d/pull/56

**Comment by da2ce7** [comment]
Updated with a more robust process and better documentation.

**Comment by da2ce7** [comment]
closed for new issue: https://github.com/fract4d/gnofract4d/issues/84
