### ISSUE TITLE
Move Gnofract4d to a Github Organisation

### ISSUE THREAD

**Issue by da2ce7** [fract4d/gnofract4d#58]
Please consider creating a GnoFract4d Organisation on Github.

I am happy to do this, however to keep all the issue and pull request history nice, it is best to 'move' this repo to the new organisation on GitHub, for this process I will need the direct support from @edyoung .

**Comment by edyoung** [comment]
Why would this be helpful?

**Comment by da2ce7** [comment]
@edyoung I suggest that the main reason that creating an organisation would be helpful for this project is that you are poor on time, and using the organisation you could delegate out roles to other people.

For example, I could do the manual work needed to adjust the project over to cvs (described in https://github.com/edyoung/gnofract4d/issues/57 )

Other aspects such as integrating new automated tools such as lint or a merge-bot could be considered and implemented without your direct focus and time-cost.

**Comment by edyoung** [comment]
done
