### ISSUE TITLE
Can't import required module

### ISSUE THREAD

**Issue by davidannis098** [fract4d/gnofract4d#6]
Installed on Mac OSX 10.11.6 When I try to run gnofract I get
[MacBook-Pro-3:~/gnofract4d-V_3_14_1] davidannis% ./gnofract4d

Can't import a required module.
If you haven't set up Gnofract 4D yet, run './setup.py build'
Error was: 'dlopen(/Users/davidannis/gnofract4d-V_3_14_1/fract4d/fract4dc.so, 2): Library not loaded: /opt/local/lib/libpng12.0.dylib
  Referenced from: /Users/davidannis/gnofract4d-V_3_14_1/fract4d/fract4dc.so
  Reason: image not found' 

I have run build. There is a libpng12.0.dylib on my system in /opt/x11/lib/

**Comment by edyoung** [comment]
Hi David. Sorry for the trouble. Unfortunately I don't have a working mac environment at the moment so it's a bit tricky to diagnose. You could try copying the libpng library to /opt/local/lib, or change the library load path to include the directory where it already is.

**Comment by jameshiew** [comment]
Probably missing some libraries that can be installed from homebrew (e.g. `brew install libpng`)

**Comment by edyoung** [comment]
Closing as stale. Other users report they are able to use Mac OS successfully

**Comment by alazir4** [comment]
Good day! It's very strange, but I face just the same situation on my Mac in Mac OS 26.1.
After loading dependencies with brew and making compilation, I still get 

alazir@iMac-iMac gnofract4d-4.4 % ./gnofract4d
Can't import a required module.
If you haven't set up Gnofract 4D yet, run:
  meson setup _build
  meson compile -C _build

Error was: 'cannot import name 'fract4dc' from 'fract4d' (/Users/alazir/Downloads/gnofract4d-4.4/fract4d/__init__.py)'
