### ISSUE TITLE
Updated website. Any comments here!

### ISSUE THREAD

**Issue by edyoung** [fract4d/gnofract4d#88]
The streamlined web site is now live at https://fract4d.github.io/gnofract4d/

The idea is to put useful stuff in the readme and wiki, and just have this a place where people can find the program, so it's basically just a landing page right now. 

Let me know of issues or suggestions.

**Comment by DX-MON** [comment]
It's looking good! My only suggestion for now is perhaps provide a switchable dark theme for a more accessible site.

**Comment by mindhells** [comment]
Looks nice!
Maybe it doesn't make sense for a website to download a desktop app, but it would be cool to add responsive views.

**Comment by josecelano** [comment]
I would keep the old one in parallel (if possible) until the contents are moved to the wiki. If there is not an easy way to read it. I used to check it frequently especially the basic concepts (4D) and the formula language parts. Maybe as someone proposed in the past we could create a new repo for the old site an mark it as deprecated or "under construction".

**Comment by edyoung** [comment]
I will work on including the docs on the website next. Making it switch to a single-column layout on a small screen should be doable. Not sure I will get to switchable themes any time soon, I find it painful enough to get HTML working at all ;-)

**Comment by edyoung** [comment]
The docs are up now, and I also made it collapse to a single column for narrow/mobile screens.
