### ISSUE TITLE
Installed Gnofract 4D 4.1 fails to start - No such file or directory: 'fract4d/c/pf.h'

### ISSUE THREAD

**Issue by cjmayo** [fract4d/gnofract4d#90]
https://github.com/fract4d/gnofract4d/blob/b3b1bff199d4cce3a3bbe1d13ae7103e1ce7be3c/fract4d_compiler/codegen.py#L243-L244

codegen.py is installed by setup.py in:

"/usr/lib/python3.8/site-packages/fract4d_compiler/codegen.py"

and is trying to open files that aren't installed from a relative path that doesn't exist.

**Comment by edyoung** [comment]
#91
